<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /home/seamus/buildkit/build/wp-demo/web/wp-content/uploads/civicrm/ext/biz.jmaconsulting.grantapplications/xml/schema/CRM/Grantapplications/GrantApplicationPage.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:348d9c93fde38cf497d415b93196ea66)
 */

/**
 * Database access object for the GrantApplicationPage entity.
 */
class CRM_Grant_DAO_GrantApplicationPage extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_grant_app_page';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique GrantApplicationPage ID
   *
   * @var int
   */
  public $id;

  /**
   * @var string
   */
  public $title;

  /**
   * @var text
   */
  public $intro_text;

  /**
   * @var text
   */
  public $footer_text;

  /**
   * Type of grant. Implicit FK to civicrm_option_value in grant_type option_group.
   *
   * @var int
   */
  public $grant_type_id;

  /**
   * Price field option amount
   *
   * @var float
   */
  public $default_amount;

  /**
   * @var bool
   */
  public $is_draft;

  /**
   * @var string
   */
  public $draft_title;

  /**
   * @var text
   */
  public $draft_text;

  /**
   * @var text
   */
  public $draft_footer;

  /**
   * @var string
   */
  public $thankyou_title;

  /**
   * @var text
   */
  public $thankyou_text;

  /**
   * @var text
   */
  public $thankyou_footer;

  /**
   * @var bool
   */
  public $is_email_receipt;

  /**
   * @var string
   */
  public $receipt_from_name;

  /**
   * @var string
   */
  public $receipt_from_email;

  /**
   * @var string
   */
  public $cc_receipt;

  /**
   * @var string
   */
  public $bcc_receipt;

  /**
   * @var text
   */
  public $receipt_text;

  /**
   * @var bool
   */
  public $is_active;

  /**
   * @var datetime
   */
  public $start_date;

  /**
   * @var datetime
   */
  public $end_date;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $created_id;

  /**
   * Date and time that event was created.
   *
   * @var datetime
   */
  public $created_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_grant_app_page';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   */
  public static function getEntityTitle() {
    return ts('Grant Application Pages');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'created_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Grantapplications_ExtensionUtil::ts('Unique GrantApplicationPage ID'),
          'required' => TRUE,
          'where' => 'civicrm_grant_app_page.id',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Title'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_grant_app_page.title',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'text',
          ],
          'add' => NULL,
        ],
        'intro_text' => [
          'name' => 'intro_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Intro Text'),
          'rows' => 4,
          'cols' => 60,
          'where' => 'civicrm_grant_app_page.intro_text',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.8',
        ],
        'footer_text' => [
          'name' => 'footer_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Footer Text'),
          'rows' => 4,
          'cols' => 60,
          'where' => 'civicrm_grant_app_page.footer_text',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.8',
        ],
        'grant_type_id' => [
          'name' => 'grant_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Grant Type'),
          'description' => CRM_Grantapplications_ExtensionUtil::ts('Type of grant. Implicit FK to civicrm_option_value in grant_type option_group.'),
          'required' => TRUE,
          'where' => 'civicrm_grant_app_page.grant_type_id',
          'export' => TRUE,
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'grant_type',
            'optionEditPath' => 'civicrm/admin/options/grant_type',
          ],
          'add' => '1.8',
        ],
        'default_amount' => [
          'name' => 'default_amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Amount'),
          'description' => CRM_Grantapplications_ExtensionUtil::ts('Price field option amount'),
          'precision' => [
            20,
            2,
          ],
          'where' => 'civicrm_grant_app_page.default_amount',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '1.8',
        ],
        'is_draft' => [
          'name' => 'is_draft',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'where' => 'civicrm_grant_app_page.is_draft',
          'default' => '0',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'draft_title' => [
          'name' => 'draft_title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Draft Title'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_grant_app_page.draft_title',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'text',
          ],
          'add' => NULL,
        ],
        'draft_text' => [
          'name' => 'draft_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Draft Text'),
          'rows' => 8,
          'cols' => 60,
          'where' => 'civicrm_grant_app_page.draft_text',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.8',
        ],
        'draft_footer' => [
          'name' => 'draft_footer',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Draft Footer'),
          'rows' => 8,
          'cols' => 60,
          'where' => 'civicrm_grant_app_page.draft_footer',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.8',
        ],
        'thankyou_title' => [
          'name' => 'thankyou_title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Thankyou Title'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_grant_app_page.thankyou_title',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'text',
          ],
          'add' => NULL,
        ],
        'thankyou_text' => [
          'name' => 'thankyou_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Thankyou Text'),
          'rows' => 8,
          'cols' => 60,
          'where' => 'civicrm_grant_app_page.thankyou_text',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.8',
        ],
        'thankyou_footer' => [
          'name' => 'thankyou_footer',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Thankyou Footer'),
          'rows' => 8,
          'cols' => 60,
          'where' => 'civicrm_grant_app_page.thankyou_footer',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.8',
        ],
        'is_email_receipt' => [
          'name' => 'is_email_receipt',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'where' => 'civicrm_grant_app_page.is_email_receipt',
          'default' => '0',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'receipt_from_name' => [
          'name' => 'receipt_from_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Receipt From Name'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_grant_app_page.receipt_from_name',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'receipt_from_email' => [
          'name' => 'receipt_from_email',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Receipt From Email'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_grant_app_page.receipt_from_email',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'cc_receipt' => [
          'name' => 'cc_receipt',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Cc Receipt'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_grant_app_page.cc_receipt',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'bcc_receipt' => [
          'name' => 'bcc_receipt',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Bcc Receipt'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_grant_app_page.bcc_receipt',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'receipt_text' => [
          'name' => 'receipt_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Receipt Text'),
          'rows' => 6,
          'cols' => 50,
          'where' => 'civicrm_grant_app_page.receipt_text',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '1.8',
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'where' => 'civicrm_grant_app_page.is_active',
          'default' => '1',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => '1.8',
        ],
        'grant_app_start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Grant Application Page Start Date'),
          'import' => TRUE,
          'where' => 'civicrm_grant_app_page.start_date',
          'headerPattern' => '/^start|(s(tart\s)?date)$/i',
          'export' => TRUE,
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => '1.7',
        ],
        'grant_app_end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Grant Application Page End Date'),
          'import' => TRUE,
          'where' => 'civicrm_grant_app_page.end_date',
          'headerPattern' => '/^end|(e(nd\s)?date)$/i',
          'export' => TRUE,
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => '1.7',
        ],
        'created_id' => [
          'name' => 'created_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Grantapplications_ExtensionUtil::ts('FK to Contact'),
          'where' => 'civicrm_grant_app_page.created_id',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => CRM_Grantapplications_ExtensionUtil::ts('Event Created Date'),
          'description' => CRM_Grantapplications_ExtensionUtil::ts('Date and time that event was created.'),
          'where' => 'civicrm_grant_app_page.created_date',
          'table_name' => 'civicrm_grant_app_page',
          'entity' => 'GrantApplicationPage',
          'bao' => 'CRM_Grant_DAO_GrantApplicationPage',
          'localizable' => 0,
          'add' => '3.0',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'grant_app_page', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'grant_app_page', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
