-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_grant_app_page`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_grant_app_page
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_grant_app_page` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique GrantApplicationPage ID',
     `title` varchar(255)    ,
     `intro_text` text    ,
     `footer_text` text    ,
     `grant_type_id` int unsigned NOT NULL   COMMENT 'Type of grant. Implicit FK to civicrm_option_value in grant_type option_group.',
     `default_amount` decimal(20,2)    COMMENT 'Price field option amount',
     `is_draft` tinyint   DEFAULT 0 ,
     `draft_title` varchar(255)    ,
     `draft_text` text    ,
     `draft_footer` text    ,
     `thankyou_title` varchar(255)    ,
     `thankyou_text` text    ,
     `thankyou_footer` text    ,
     `is_email_receipt` tinyint   DEFAULT 0 ,
     `receipt_from_name` varchar(255)    ,
     `receipt_from_email` varchar(255)    ,
     `cc_receipt` varchar(255)    ,
     `bcc_receipt` varchar(255)    ,
     `receipt_text` text    ,
     `is_active` tinyint   DEFAULT 1 ,
     `start_date` datetime    ,
     `end_date` datetime    ,
     `created_id` int unsigned    COMMENT 'FK to Contact',
     `created_date` datetime    COMMENT 'Date and time that event was created.' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_grant_app_page_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE  
)    ;

 